### ISSUE TITLE
it does not work on current octoprint 

### ISSUE THREAD

**Issue by jane-rose** [ron-linkertech/octoprint-snapmaker-control#2]
i try to resume it and change it adapt to snapmaker 2.
but it does not work on current octoprint  version 1.3.0

**Comment by jane-rose** [comment]
![image](https://user-images.githubusercontent.com/33253363/84152518-5de08400-aa97-11ea-9e6c-ff1d43671f0f.png)

**Comment by Schnapsmaker** [comment]
Tested this tody, but it does nothing, The configscreen shows nothing. Is it still under development? Dont think so.
But it would be nice to control SM2s laser via octoprint. I am using Version 1.5.3.
